name: Build and Publish

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # SETUP AND BUILD
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install modules
        run: npm install
        env:
          CI: true
      - name: Lint
        run: npm run lint
        env:
          CI: true
      - name: Build package
        run: npm run build
        env:
          CI: true

      # PUBLISH PACKAGE
      - name: Semantic release
        if: github.ref == 'refs/heads/main'
        uses: cycjimmy/semantic-release-action@v2
        with:
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      # PUBLISH DOCS
      - name: Publish Storybook to GH Pages
        if: github.ref == 'refs/heads/main'
        run: npm run deploy-storybook-ci
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
